[knx-installer] * implement initial (optional) distro-defaults support.   - parse $DEFAULT_USER from passwd. * clean up $HOME for all distros. * make chown usage POSIX compatible. * remove obsolete references to /etc/sysconfig/live. * use perl to configure /etc/kernel-pkg.conf. * use section: admin. * remove non fatal lintian errors from overrides. * minor re- indent in ./knoppix-insta

diff --git a/knoppix-installer b/knoppix-installer
--- a/knoppix-installer
+++ b/knoppix-installer
@@ -7,6 +7,7 @@
 # Author: Fabian Franz <knoppix-installer@fabian-franz.de>
 #
 # Fixes and help by: Joerg Schirottke <master@kanotix.de>
+#                    Stefan Lippers-Hollmann <s.l-h@gmx.de>
 #
 # Based on work by Christian Perle & Klaus Knopper
 #
@@ -23,28 +24,51 @@ LOG="$HOME/.knofig_log"
 TARGET_MNT_POINT="/mnt/hdinstall" # TR1 in old installer
 TARGET_MNT_NAME="hdinstall" # TR1 in old installer
 
-DEFAULT_USER="knoppix"
-DEFAULT_NAME="Kanotix User"
-DEFAULT_DIR="KNOPPIX"
+# make use of distro-defaults
+if [ -f /etc/defaults/distro ]; then
+	source /etc/defaults/distro
 
-# This is not Kano's Kanotix
-if [ -e /etc/kanotix-version ]; then
-	#DISTRO="Kanotix"	# currently not in use
-	INSTALL_KANO="yes"
+	[ -n "$FLL_LIVE_USER" ] && DEFAULT_USER="$FLL_LIVE_USER" || DEFAULT_USER="knoppix"
+	[ -n "$FLL_MEDIA_DIR" ] && DEFAULT_DIR="$FLL_MEDIA_DIR"  || DEFAULT_DIR="KNOPPIX"
 else
-	#DISTRO="Kanotix"	# currently not in use
-	INSTALL_KANO="no"
+	DEFAULT_USER="knoppix"
+	DEFAULT_DIR="KNOPPIX"
 fi
+
+DEFAULT_NAME=$(getent passwd "$DEFAULT_USER" | cut -f5 -d: | cut -f1 -d,)
+
+if [ -n "$FLL_DISTRO_NAME" ]; then
+	# use distro-defaults to determine the distribution name
+	case "$FLL_DISTRO_NAME" in
+		[kK][aA][nN][oO][tT][iI][xX]*)
+			INSTALL_KANO="yes"
+			;;
+		[kK][nN][oO][pP][pP][iI][xX]*)
+			INSTALL_KANO="no"
+			;;
+		*)
+			INSTALL_KANO="no"
+			;;
+	esac
+else
+	# judge based on /etc/kanotix-version
+	if [ -e /etc/kanotix-version ]; then
+		INSTALL_KANO="yes"
+	else
+		INSTALL_KANO="no"
+	fi
+fi
+
 
 [ -f /proc/cmdline ] || mount -t proc proc /proc 2>/dev/null
 
-MEM_SWAP_NEEDED=$((512*1000)) # need some lower so that people that have 512 MB can use this option
+MEM_SWAP_NEEDED=$((512*1000)) # need some lower so that people with 512 MB can use this option
 SWAP_MIN=$((128*1024))
 if grep -q unionfs /proc/mounts; then
-ROOT_MIN_RAW=$(du -sm "/$DEFAULT_DIR" | awk '{print $1}')
+	ROOT_MIN_RAW=$(du -sm "/$DEFAULT_DIR" | awk '{print $1}')
 else
-ROOT_MIN_RAW=$(df -m "/$DEFAULT_DIR" | tail -1 | awk '{print $3}')
-grep -q squashfs /proc/mounts && ROOT_MIN_RAW=$(($ROOT_MIN_RAW*270/100)) #fix status bar for squashfs
+	ROOT_MIN_RAW=$(df -m "/$DEFAULT_DIR" | tail -1 | awk '{print $3}')
+	grep -q squashfs /proc/mounts && ROOT_MIN_RAW=$(($ROOT_MIN_RAW*270/100)) #fix status bar for squashfs
 fi
 ROOT_MIN_CORR=$[ROOT_MIN_RAW*115/100] # + 15% Filesystem overhead
 ROOT_MIN=$(($ROOT_MIN_CORR*1024))
@@ -61,11 +85,10 @@ SEARCHPATH="/usr/share/knoppix-installer"
 [ -f ./modules/00-knoppix-utils.bm ] && SEARCHPATH="."
 
 # workaround for buggy knoppix-installer-latest-web and self-made installations
-[ "$SEARCHPATH" = "." ] && chown -R root.root .
+[ "$SEARCHPATH" = "." ] && chown -R root:root .
 
-for i in $(find $SEARCHPATH -name "*.bm")
-do
-  . $i
+for i in $(find $SEARCHPATH -name "*.bm"); do
+	source $i
 done
 
 #
@@ -73,42 +96,42 @@ done
 #
 
 clean_exit(){
-  [ -n "$TMPDIR" ] && rm -rf "$TMPDIR"
-  logit $"knoppix-installer terminated"
-  logit
+	[ -n "$TMPDIR" ] && rm -rf "$TMPDIR"
+	logit $"knoppix-installer terminated"
+	logit
 }
 
 trap clean_exit EXIT
 
 function logit
 {
-  TIME=$(date)
-  [ -n "$*" ] && echo $TIME: "$@" >> $LOG || echo >> $LOG
+	TIME=$(date)
+	[ -n "$*" ] && echo $TIME: "$@" >> $LOG || echo >> $LOG
 }
 
 function exit_proc
 {
-  unset IFS
-  $DIALOG --backtitle "$BT" --title $"Save configuration?" --yesno $"Do you want to save your configuration?" 10 60
-  RC=$?
-  [ $RC -eq 0 ] && save_config $CONFIG_FILE # save of configuration
-  [ $RC -ne 255 ] && exit 0
-  RC=0
+	unset IFS
+	$DIALOG --backtitle "$BT" --title $"Save configuration?" --yesno $"Do you want to save your configuration?" 10 60
+	RC=$?
+	[ $RC -eq 0 ] && save_config $CONFIG_FILE # save of configuration
+	[ $RC -ne 255 ] && exit 0
+	RC=0
 }
 
 function setup_dialog_messages()
 {
-  MAX=5 # number of steps
+	MAX=5 # number of steps
 
-  BT=$"Kanotix Installation"" (v$VERSION)"
-  DT=$"Installation of Kanotix to harddisk (Step 0/$MAX)"
-  INIT_T=$"Initialisation of Kanotix-Installation"
-  T1=$INIT_T
-  ET=$"Installation failed"
-  ST=$"Installation successfull"
-  FATAL_DIALOG=$"Fatal dialog error"
+	BT=$"Kanotix Installation"" (v$VERSION)"
+	DT=$"Installation of Kanotix to harddisk (Step 0/$MAX)"
+	INIT_T=$"Initialisation of Kanotix-Installation"
+	T1=$INIT_T
+	ET=$"Installation failed"
+	ST=$"Installation successfull"
+	FATAL_DIALOG=$"Fatal dialog error"
 
-  N=1; # Step 1
+	N=1; # Step 1
 }
 
 setup_dialog "knoppix-installer" # FIXME! Check for Commandline-Params
@@ -120,16 +143,15 @@ setup_dialog_messages
 
 function add_var
 {
-  case "$REGISTERED" in *$1*) return 1;; esac
-  REGISTERED="$REGISTERED $1"
+	case "$REGISTERED" in *$1*) return 1;; esac
+	REGISTERED="$REGISTERED $1"
 }
 
 function register_vars
 {
-  for i in $@;
-  do
-    add_var "$i"
-  done
+	for i in $@; do
+		add_var "$i"
+	done
 }
 
 #
@@ -138,17 +160,17 @@ function register_vars
 
 function register_var
 {
-  export $1"_COMMENT"="$2"
-  export $1"_ALLOWED"="$3"
-  export $1"_CHECKIT"="$4"
-  export $1"_DEFAULT"="$5"
-  [ -z "${!1}" -a -n "$5" ] && export $1="$5"
+	export $1"_COMMENT"="$2"
+	export $1"_ALLOWED"="$3"
+	export $1"_CHECKIT"="$4"
+	export $1"_DEFAULT"="$5"
+	[ -z "${!1}" -a -n "$5" ] && export $1="$5"
 }
 
 function update_status
 {
-  echo -e "XXX\n$*\nXXX"
-  logit "$*"
+	echo -e "XXX\n$*\nXXX"
+	logit "$*"
 }
 
 
@@ -166,163 +188,147 @@ MODULES_LOAD="hd swap services boot system"
 
 function create_config
 {
-  T1=$"Choose System Type"
+	T1=$"Choose System Type"
   
-  # Configure system as the _very_ first
-  # TODO: How to get back there ...
+	# Configure system as the _very_ first
+	# TODO: How to get back there ...
 
-  module_system 0 || return 1
-  if [ "$SYSTEM_MODULE" == "configured" ]
-  then
-  	# Set MODULES / NUM_MODULES for the configured system type.
-  	module_system_set_modules
-  fi
+	module_system 0 || return 1
+	if [ "$SYSTEM_MODULE" == "configured" ]; then
+		# Set MODULES / NUM_MODULES for the configured system type.
+		module_system_set_modules
+	fi
   
-  NUM_REAL_MODULES=$[$NUM_MODULES-$MODULES_NUMAUTO]
-  T1=$"Creating Kanotix Configuration Step (0/$NUM_REAL_MODULES)"
-  N=1
-  I=0
-  DIR=0
-  while [ "$I" -lt "$NUM_MODULES" ];
-  do
-    "module_${MODULES[$I]}" $DIR
-    RC=$?
-    DIR=0
-    [ $RC -eq 1 ] && DIR=-1
-    [ $RC -eq 0 ] && DIR=1
-    I=$[$I+$DIR]
-    [ $I -lt 0 ] && return 1
-    stringinstring "${MODULES[$I]}" "$MODULES_AUTO" || N=$[$N+$DIR]
-  done
-  INSTALL_READY="yes"
-  register_vars "INSTALL_READY"
-  return 0
+	NUM_REAL_MODULES=$[$NUM_MODULES-$MODULES_NUMAUTO]
+	T1=$"Creating Kanotix Configuration Step (0/$NUM_REAL_MODULES)"
+	N=1
+	I=0
+	DIR=0
+	while [ "$I" -lt "$NUM_MODULES" ]; do
+		"module_${MODULES[$I]}" $DIR
+		RC=$?
+		DIR=0
+		[ $RC -eq 1 ] && DIR=-1
+		[ $RC -eq 0 ] && DIR=1
+		I=$[$I+$DIR]
+		[ $I -lt 0 ] && return 1
+		stringinstring "${MODULES[$I]}" "$MODULES_AUTO" || N=$[$N+$DIR]
+	done
+	INSTALL_READY="yes"
+	register_vars "INSTALL_READY"
+	return 0
 }
 
 function check_param
 {
-  TEMP=$(eval echo \$$1"_ALLOWED")
-  if [ -n "$TEMP" ]
-  then
-    if ! stringinstring "$2|" "$TEMP|"
-    then
-      DEFAULT_TEMP=$(eval echo \$$1"_DEFAULT")
-      msgbox $"Error: Unknown value $2 for $1\nSetting to default value ($DEFAULT_TEMP)." 10 60
-      export "$1"="$DEFAULT_TEMP"
-      logit $"Error: Unknown value $2 for $1\nSetting to default value ($DEFAULT_TEMP)."
-    fi
-  fi
-  
-  TEMP=$(eval echo \$$1"_CHECKIT")
-  if [ -n "$TEMP" ]
-  then
-    if ! $TEMP
-    then
-      msgbox $"Error: Check failed for $1 ($2)\nThe configuration module will now be started." 10 60
-      export "$1"=""
-      logit $"Error: Check failed for $1 ($2)\nThe configuration module will now be started."
+	TEMP=$(eval echo \$$1"_ALLOWED")
+	if [ -n "$TEMP" ]; then
+		if ! stringinstring "$2|" "$TEMP|"; then
+			DEFAULT_TEMP=$(eval echo \$$1"_DEFAULT")
+			msgbox $"Error: Unknown value $2 for $1\nSetting to default value ($DEFAULT_TEMP)." 10 60
+			export "$1"="$DEFAULT_TEMP"
+			logit $"Error: Unknown value $2 for $1\nSetting to default value ($DEFAULT_TEMP)."
+		fi
+	fi
 
-      RC=1
-      while [ "$RC" -eq "1" ]
-      do
-        ${TEMP/_check/} 1
-        RC=$?
-      done
-    fi
-  fi
-  return 0
+	TEMP=$(eval echo \$$1"_CHECKIT")
+	if [ -n "$TEMP" ]; then
+		if ! $TEMP; then
+			msgbox $"Error: Check failed for $1 ($2)\nThe configuration module will now be started." 10 60
+			export "$1"=""
+			logit $"Error: Check failed for $1 ($2)\nThe configuration module will now be started."
+
+			RC=1
+			while [ "$RC" -eq "1" ]; do
+				${TEMP/_check/} 1
+				RC=$?
+			done
+		fi
+	fi
+	return 0
 }
 
 function load_config
 {
-  T1=$"Loading Kanotix configuration"
-  if [ -z "$1" ]
-  then
-    wizard $"Here you can input a filename to load an existing configuration" --inputbox $"Input the configuration filename to be loaded" 10 60 "$CONFIG_USER"
-    [ $? -ne 0 ] && return 1
-    CONFIG_USER=$(cat $TMP)
-    if [ ! -r "$CONFIG_USER" ]
-    then
-      msgbox $"File $CONFIG_USER could not be found. The loading of the configuration will be aborted." 10 60
-      return 1
-    fi
-    set -- "$CONFIG_USER"
-  fi
-  logit "$T1 $1"
-  . $1
+	T1=$"Loading Kanotix configuration"
+	if [ -z "$1" ]; then
+		wizard $"Here you can input a filename to load an existing configuration" --inputbox $"Input the configuration filename to be loaded" 10 60 "$CONFIG_USER"
+		[ $? -ne 0 ] && return 1
+		CONFIG_USER=$(cat $TMP)
+		if [ ! -r "$CONFIG_USER" ]; then
+			msgbox $"File $CONFIG_USER could not be found. The loading of the configuration will be aborted." 10 60
+			return 1
+		fi
+		set -- "$CONFIG_USER"
+	fi
+	logit "$T1 $1"
+	source $1
 
-  for i in $MODULES_LOAD
-  do
-    "module_${i}_defaults"
-  done
+	for i in $MODULES_LOAD; do
+		"module_${i}_defaults"
+	done
   
-  for i in $REGISTERED; 
-  do
-    #echo "$i=${!i}"
-    #echo check_param "$i" "${!i}"
-    check_param "$i" "${!i}"
-  done
+	for i in $REGISTERED; do
+		#echo "$i=${!i}"
+		#echo check_param "$i" "${!i}"
+		check_param "$i" "${!i}"
+	done
 }
 
 function save_config
 {
-  T1=$"Saving Kanotix configuration"
-  if [ -z "$1" ]
-  then
-    wizard $"Here you can input a filename to save the configuration" --inputbox $"Input a filename for the configuration" 10 60 "$CONFIG_USER"
-    [ $? -ne 0 ] && return 1
-    CONFIG_USER=$(cat $TMP)
-    [ -z "$CONFIG_USER" ] && return 1
-    if [ -r "$CONFIG_USER" ]
-    then
-      wizard $"If you click yes, the file will be overwritten, otherwise this script will abort" --defaultno --yesno $"Do you really want to overwrite $CONFIG_USER?" 10 60
-      [ $? -ne 0 ] && return 1
-    fi
-    set -- "$CONFIG_USER"
-  fi
-  logit "$T1 $1"
-  echo "REGISTERED='$REGISTERED'" > $1
-  for i in $REGISTERED; 
-  do
-    [ "${!i}" = "configured" ] && echo "" >> $1
-    TEMP=$(eval echo \$$i"_COMMENT")
-    [ -n "$TEMP" ] && echo "# $TEMP" >> $1
-    TEMP=$(eval echo \$$i"_ALLOWED")
-    [ -n "$TEMP" ] && echo "#" $"Possible are:" $TEMP >> $1
-    TEMP=$(eval echo \$$i"_CHECKIT")
-    [ -n "$TEMP" ] && echo "#" $"This value will be checked by function" $TEMP >> $1
-    TEMP=$(eval echo \$$i"_DEFAULT")
-    [ -n "$TEMP" ] && echo "#" $"Default value is:" $TEMP >> $1
-    
-    echo "$i='${!i}'" >> $1
-  done
+	T1=$"Saving Kanotix configuration"
+	if [ -z "$1" ]; then
+		wizard $"Here you can input a filename to save the configuration" --inputbox $"Input a filename for the configuration" 10 60 "$CONFIG_USER"
+		[ $? -ne 0 ] && return 1
+		CONFIG_USER=$(cat $TMP)
+		[ -z "$CONFIG_USER" ] && return 1
+		if [ -r "$CONFIG_USER" ]; then
+			wizard $"If you click yes, the file will be overwritten, otherwise this script will abort" --defaultno --yesno $"Do you really want to overwrite $CONFIG_USER?" 10 60
+			[ $? -ne 0 ] && return 1
+		fi
+		set -- "$CONFIG_USER"
+	fi
+	logit "$T1 $1"
+	echo "REGISTERED='$REGISTERED'" > $1
+	for i in $REGISTERED; do
+		[ "${!i}" = "configured" ] && echo "" >> $1
+		TEMP=$(eval echo \$$i"_COMMENT")
+		[ -n "$TEMP" ] && echo "# $TEMP" >> $1
+		TEMP=$(eval echo \$$i"_ALLOWED")
+		[ -n "$TEMP" ] && echo "#" $"Possible are:" $TEMP >> $1
+		TEMP=$(eval echo \$$i"_CHECKIT")
+		[ -n "$TEMP" ] && echo "#" $"This value will be checked by function" $TEMP >> $1
+		TEMP=$(eval echo \$$i"_DEFAULT")
+		[ -n "$TEMP" ] && echo "#" $"Default value is:" $TEMP >> $1
+
+		echo "$i='${!i}'" >> $1
+	done
 }
 
 function show_install_options
 {
-  echo > $TMP
-  I=0
-  # System needs an extra sausage (german limerick ;-) )
-  module_system_showinfo >> $TMP
+	echo > $TMP
+	I=0
+	# System needs an extra sausage (german limerick ;-) )
+	module_system_showinfo >> $TMP
 
-  while [ "$I" -lt "$NUM_MODULES" ]
-  do
-    "module_${MODULES[$I]}_showinfo"
-    I=$[I+1]
-  done >> $TMP
-  echo "" >> $TMP
-  echo $"Several of this options can only be changed in the Configurationfile $CONFIG_FILE." >> $TMP
-  echo $"The Installation will now be started. The author and knopper.net give no warranty against any damage caused by this script." >> $TMP
-  echo "" >> $TMP
-  echo $"Do you want to proceed with these parameters?" >> $TMP
-  DISP_TEXT=$(cat $TMP)
-  wizard $"Make sure you agree to all parameters, if so proceed with the installation." --defaultno --yesno "$DISP_TEXT" 35 60
+	while [ "$I" -lt "$NUM_MODULES" ]; do
+		"module_${MODULES[$I]}_showinfo"
+		I=$[I+1]
+	done >> $TMP
+	echo "" >> $TMP
+	echo $"Several of this options can only be changed in the Configurationfile $CONFIG_FILE." >> $TMP
+	echo $"The Installation will now be started. The author and knopper.net give no warranty against any damage caused by this script." >> $TMP
+	echo "" >> $TMP
+	echo $"Do you want to proceed with these parameters?" >> $TMP
+	DISP_TEXT=$(cat $TMP)
+	wizard $"Make sure you agree to all parameters, if so proceed with the installation." --defaultno --yesno "$DISP_TEXT" 35 60
 }
 
 function old_installer
 {
-	if [ "$SYSTEM_TYPE" = "knoppix" ]
-	then
+	if [ "$SYSTEM_TYPE" = "knoppix" ]; then
 		system_type_knoppix
 		return 0
 	fi
@@ -342,80 +348,73 @@ function old_installer
 
 function do_install
 {
-  echo ""
-  INSTALL_LIST="module_hd_doaction module_swap_doaction update_fstab old_installer add_bootmanager :"
-  INSTALL_LIST_NUM=$[6-1]
-  N=0;
-  for i in $INSTALL_LIST
-  do
-    echo $[$N*100/$INSTALL_LIST_NUM]
-    "${i}"
-    [ $? -ne 0 ] && return 1
-    N=$[$N+1]
-  done
-  return 0
+	echo ""
+	INSTALL_LIST="module_hd_doaction module_swap_doaction update_fstab old_installer add_bootmanager :"
+	INSTALL_LIST_NUM=$[6-1]
+	N=0;
+	for i in $INSTALL_LIST; do
+		echo $[$N*100/$INSTALL_LIST_NUM]
+		"${i}"
+		[ $? -ne 0 ] && return 1
+		N=$[$N+1]
+	done
+	return 0
 }
 
 function start_install
 {
- if [ -z "$INSTALL_READY" ]
- then
-   create_config
-   [ $? -ne 0 ] && return 1
- fi
- T1=$"Starting Kanotix installation"
- if [ -z "$INSTALL_READY" ];
- then
-   msgbox $"Error: No complete Configuration found" 10 60
-   return 1
- fi
- show_install_options
- [ $? -ne 0 ] && return 1
- touch $TMPDIR/errors
- save_config $CONFIG_FILE
- T1=$"Starting Kanotix installation"
- do_install | $DIALOG --backtitle "$BT" --title "$T1" --gauge $"Installing" 10 60
- RC=$?
- MODULE_ERROR=$(<$TMPDIR/errors)
- if [ -n "$MODULE_ERROR" ]
- then
-   msgbox "Error: $MODULE_ERROR" 10 60
-   return 1
- fi
- [ $RC -ne "0" ] && return 1
+	if [ -z "$INSTALL_READY" ]; then
+		create_config
+		[ $? -ne 0 ] && return 1
+	fi
+	T1=$"Starting Kanotix installation"
+	if [ -z "$INSTALL_READY" ]; then
+		msgbox $"Error: No complete Configuration found" 10 60
+		return 1
+	fi
+	show_install_options
+	[ $? -ne 0 ] && return 1
+	touch $TMPDIR/errors
+	save_config $CONFIG_FILE
+	T1=$"Starting Kanotix installation"
+	do_install | $DIALOG --backtitle "$BT" --title "$T1" --gauge $"Installing" 10 60
+	RC=$?
+	MODULE_ERROR=$(<$TMPDIR/errors)
+	if [ -n "$MODULE_ERROR" ]; then
+		msgbox "Error: $MODULE_ERROR" 10 60
+		return 1
+	fi
+	[ $RC -ne "0" ] && return 1
 
- #
- # FLOPPY DISK!
- #
+	#
+	# FLOPPY DISK!
+	#
 
- if [ "$BOOT_DISK" = "yes" ]
- then
-   $DIALOG --backtitle "$BT" --title $"Creating floppy disk" --defaultno --yesno $"Please insert now an empty floppy disk into your floppydrive. Warning: All data on it will be lost. If you don't want to create a disk you can choose No." 0 0
-   if [ $? -eq 0 ]
-   then
-     make_floppy
-   fi
- fi
+	if [ "$BOOT_DISK" = "yes" ]; then
+		$DIALOG --backtitle "$BT" --title $"Creating floppy disk" --defaultno --yesno $"Please insert now an empty floppy disk into your floppydrive. Warning: All data on it will be lost. If you don't want to create a disk you can choose No." 0 0
+		if [ $? -eq 0 ]; then
+			make_floppy
+		fi
+	fi
 
- # /var/tmp workaround
- chmod 777 $TARGET_MNT_POINT/var/tmp
+	# /var/tmp workaround
+	chmod 777 $TARGET_MNT_POINT/var/tmp
 
- for i in $HD_MAP
- do
-   point=$(echo $i | cut -d":" -f2)
-   umount $TARGET_MNT_POINT$point
- done
+	 for i in $HD_MAP; do
+		point=$(echo $i | cut -d":" -f2)
+		umount $TARGET_MNT_POINT$point
+	done
 		      
- # Just to be sure :-)
- #umount $TARGET_MNT_POINT/proc
- umount $TARGET_MNT_POINT
- # Success Message and end installer
- #T1=$"Success!"
- T1=$ST
+	# Just to be sure :-)
+	#umount $TARGET_MNT_POINT/proc
+	umount $TARGET_MNT_POINT
+	# Success Message and end installer
+	#T1=$"Success!"
+	T1=$ST
  
- msgbox $"Kanotix was successfully installed to hd." 15 60
- logit $"Kanotix was successfully installed to hd."
- exit 0
+	msgbox $"Kanotix was successfully installed to hd." 15 60
+	logit $"Kanotix was successfully installed to hd."
+	exit 0
 }
 
 function menu_main
@@ -454,9 +453,8 @@ done
 logit $"Partition check succeeded"
 [ -f "$CONFIG_FILE" ] && load_config $CONFIG_FILE # auto load of configuration
 
-while true;
-do
-  menu_main
+while true; do
+	menu_main
 done
 }
 
@@ -467,54 +465,49 @@ done
 
 function ni-main
 {
-  logit $"knoppix-installer started"
+	logit $"knoppix-installer started"
   
-  rebuildfstab -r
-  logit $"Partition check succeeded"
+	rebuildfstab -r
+	logit $"Partition check succeeded"
   
-  if [ ! -f "$CONFIG_FILE" ]
-  then
-  	echo $"Config file $CONFIG_FILE could not be found. This is necessary for non-interactive mode."
-  	return
-  fi
-  load_config $CONFIG_FILE # auto load of configuration
+	if [ ! -f "$CONFIG_FILE" ]; then
+		echo $"Config file $CONFIG_FILE could not be found. This is necessary for non-interactive mode."
+		return
+	fi
+	load_config $CONFIG_FILE # auto load of configuration
  
-  touch $TMPDIR/errors
-  T1=$"Starting Kanotix installation"
-  do_install | $DIALOG --backtitle "$BT" --title "$T1" --gauge $"Installing" 10 60
-  RC=$?
-  MODULE_ERROR=$(<$TMPDIR/errors)
+	touch $TMPDIR/errors
+	T1=$"Starting Kanotix installation"
+	do_install | $DIALOG --backtitle "$BT" --title "$T1" --gauge $"Installing" 10 60
+	RC=$?
+	MODULE_ERROR=$(<$TMPDIR/errors)
   
-  if [ -n "$MODULE_ERROR" ]
-  then
-    msgbox "Error: $MODULE_ERROR" 10 60
-    return 1
-  fi
+	if [ -n "$MODULE_ERROR" ]; then
+		msgbox "Error: $MODULE_ERROR" 10 60
+		return 1
+	fi
 
-  for i in $HD_MAP
-  do
-    point=$(echo $i | cut -d":" -f2)
-    umount $TARGET_MNT_POINT$point
-  done
+	for i in $HD_MAP; do
+		point=$(echo $i | cut -d":" -f2)
+		umount $TARGET_MNT_POINT$point
+	done
 		      
-  # Just to be sure :-)
-  #umount $TARGET_MNT_POINT/proc
-  umount $TARGET_MNT_POINT
-  # Success Message and end installer
-  logit $"Kanotix was successfully installed to hd."
-  exit 0
+	# Just to be sure :-)
+	#umount $TARGET_MNT_POINT/proc
+	umount $TARGET_MNT_POINT
+	# Success Message and end installer
+	logit $"Kanotix was successfully installed to hd."
+	exit 0
 }
 
-if [ "$1" = "--non-interactive" ]
-then
-  ni-main
-  exit 1 # something did go wrong
+if [ "$1" = "--non-interactive" ]; then
+	ni-main
+exit 1 # something did go wrong
 fi
 
-if [ $UID -eq 0 ];
-then
-  main
+if [ $UID -eq 0 ]; then
+	 main
 else
-  echo $"root permission needed."
+	echo $"root permission needed."
 fi
 
