knxinstaller (0.4.4-4) unstable; urgency=low
  * added handling of autoinstall to kanotix-update.
  * added check if / ($HD_COICE) is mounted to /isosrc in installer
    (this should not happen because the running iso could get deleted then)

 -- Andreas Loibl <andreas@andreas-loibl.de>  Tue, 19 Sep 2006 22:28:20 +0200

diff --git a/src/kanotix-check-knofig b/src/kanotix-check-knofig
--- a/src/kanotix-check-knofig
+++ b/src/kanotix-check-knofig
@@ -92,11 +92,21 @@ if [ "$HD_IGNORECHECK" != "yes" ]; then
     fi
 fi
 
+# Check if root-partition is at /isosrc
+if grep -q "^$HD_CHOICE /isosrc" /proc/mounts; then
+	echo "TAB: 1"
+	echo "ERROR: Partition $HD_CHOICE is already mounted to /isosrc!"
+	exit 1
+fi
 
 # Check if partitions of HD_MAP are formatted
 function checkFilesystem
 {
 	PARTITION="$1"
+	if grep -q "^$PARTITION " /proc/mounts; then
+		# partition is already mounted
+		return 0
+	fi
 	TMPMP="/tmp/kanotix-update.$$.$RANDOM"
 	mkdir -p "$TMPMP"
 	mount $PARTITION "$TMPMP"
